title: Data The JBoss Way
author: Ray Ploski
disqus: jboss-data
show_debug: true
tagline: Data The JBoss Way
description: Build modern applications more simply and productively.
issue_tracker: https://issues.jboss.org/browse/WAY
jboss_wiki: https://community.jboss.org/wiki
eap6_url: http://www.redhat.com/promo/eap6beta/
as7_url: http://www.jboss.org/as7
weld_url: http://seamframework.org/Weld
drools_url: http://www.jboss.org/drools
modeshape_url: http://www.jboss.org/modeshape
transactions_url: http://www.jboss.org/jbosstm
hibernate_url:  http://www.hibernate.org
infinispan_url: http://www.jboss.org/infinispan
jclouds_url: http://www.jclouds.org/


haml:
  attr_wrapper: '"'
  escape_attrs: :once
textile: ['no_span_caps']
disqus_generate_id: true
google_plusone: true

profiles:
  development:
    base_url: http://localhost:4242
  test:
    base_url: http://people.redhat.com/~rploski/data
    deploy:
      host: people.redhat.com
      path: /home/remote/rploski/public_html/data
  staging:
    jdf_url: http://www.jboss.org/data
    base_url:  http://data-ray.rhcloud.com

